
export const CANCEL_APP = 'GR_CANCEL_APP';


export const CURRENT_RECEIVER_DONE = 'GR_CURRENT_RECEIVER_DONE';
export const CURRENT_RECEIVER_FAILED = 'GR_CURRENT_RECEIVER_FAILED';

export const FINISH_DONE = 'GR_FINISH_DONE';
export const FINISH_FAILED = 'GR_FINISH_FAILED';

export const GEN_RECEIVERS_DONE = 'GR_GEN_RECEIVERS_DONE';
export const GEN_RECEIVERS_FAILED = 'GR_GEN_RECEIVERS_FAILED';

export const LOG_ENTRY_LAST_DONE = 'GR_LOG_ENTRY_LAST_DONE';
export const LOG_ENTRY_LAST_FAILED = 'GR_LOG_ENTRY_LAST_FAILED';

export const LOG_INSERT_DONE = 'GR_LOG_INSERT_DONE';
export const LOG_INSERT_FAILED = 'GR_LOG_INSERT_FAILED';

export const LOG_STEP_SET_DONE = 'GR_LOG_STEP_SET_DONE';
export const LOG_STEP_SET_FAILED = 'GR_LOG_STEP_SET_FAILED';

export const INIT = 'GR_INIT';

export const PO_STATUS_UPDATE_DONE = 'GR_PO_STATUS_UPDATE_DONE';
export const PO_STATUS_UPDATE_FAILED = 'GR_PO_STATUS_UPDATE_FAILED';


export const RCITEM_DELETE_DONE = 'GR_RCITEM_DELETE_DONE';
export const RCITEM_DELETE_FAILED = 'GR_RCITEM_DELETE_FAILED';
export const RCITEM_INSERT_DONE = 'GR_RCITEM_INSERT_DONE';
export const RCITEM_INSERT_FAILED = 'GR_RCITEM_INSERT_FAILED';
export const RCITEM_UPDATE_DONE = 'GR_RCITEM_UPDATE_DONE';
export const RCITEM_UPDATE_FAILED = 'GR_RCITEM_UPDATE_FAILED';

export const RCMAST_DELETE_DONE = 'GR_RCMAST_DELETE_DONE';
export const RCMAST_DELETE_FAILED = 'GR_RCMAST_DELETE_FAILED';
export const RCMAST_INSERT_DONE = 'GR_RCMAST_INSERT_DONE';
export const RCMAST_INSERT_FAILED = 'GR_RCMAST_INSERT_FAILED';

export const RECEIVER_COUNT_DONE = 'GR_RECEIVER_COUNT_DONE';
export const RECEIVER_COUNT_FAILED = 'GR_RECEIVER_COUNT_FAILED';

export const RECEIVERS_CRIB_DELETE_DONE = 'GR_RECEIVERS_CRIB_DELETE_DONE';
export const RECEIVERS_CRIB_DELETE_FAILED = 'GR_RECEIVERS_CRIB_DELETE_FAILED';


export const ROLLBACK_DONE = 'GR_ROLLBACK_DONE';
export const ROLLBACK_FAILED = 'GR_ROLLBACK_FAILED';

export const SET_CHECK0 = 'GR_SET_CHECK0';
export const SET_CHECK1 = 'GR_SET_CHECK1';
export const SET_CHECK2 = 'GR_SET_CHECK2';
export const SET_CHECK3 = 'GR_SET_CHECK3';

export const SET_CURRENT_RECEIVER = 'GR_SET_CURRENT_RECEIVER';
export const SET_GO_BUTTON = 'GR_SET_GO_BUTTON';
export const SET_LOGID = 'GR_SET_LOGID';
export const SET_LOG_ENTRY_LAST = 'GR_SET_LOG_ENTRY_LAST';

export const SET_POSTATUS_REPORT_PDF = 'SET_POSTATUS_REPORT_PDF';
export const SET_POSTATUS_REPORT_DONE = 'SET_POSTATUS_REPORT_DONE';
export const SET_POSTATUS_REPORT_FAILED = 'SET_POSTATUS_REPORT_FAILED';

export const SET_RCITEM = 'GR_SET_RCITEM';
export const SET_RCMAST = 'GR_SET_RCMAST';
export const SET_RCMAST_RANGE = 'GR_SET_RCMAST_RANGE';
export const SET_RCVJOIN = 'GR_SET_RCVJOIN';
export const SET_REASON = 'GR_SET_REASON';
export const SET_RECEIVER_COUNT = 'SET_RECEIVER_COUNT';

export const SET_SHIP_VIA = 'GR_SET_SHIP_VIA';
export const SET_STATE = 'GR_SET_STATE';
export const SET_STATUS = 'GR_SET_STATUS';

export const SHIP_VIA_DONE = 'GR_SHIP_VIA_DONE';
export const SHIP_VIA_FAILED = 'GR_SHIP_VIA_FAILED';

export const SQL_EXEC_DONE = 'GR_SQL_EXEC_DONE';
export const SQL_EXEC_FAILED = 'GR_SQL_EXEC_FAILED';

export const TRANS_DELETE_DONE = 'GR_TRANS_DELETE_DONE';
export const TRANS_DELETE_FAILED = 'GR_TRANS_DELETE_FAILED';

export const TRANS_INSERT_DONE = 'GR_TRANS_INS_DONE';
export const TRANS_INSERT_FAILED = 'GR_TRANS_INS_FAILED';

export const UPDATE_RCMAST_FFRTCARR= 'GR_UPDATE_RCMAST_FFRTCARR';
export const UPDATE_RCMAST_FPACKLIST= 'GR_UPDATE_RCMAST_FPACKLIST';

