// state 1 - not Started
export const NOT_STARTED = 'NOT_STARTED';

// PO With RECEIVERS
export const POWITHRECEIVERS_DATE_RANGE_NOT_READY = 'POWITHRECEIVERS_DATE_RANGE_NOT_READY';
export const POWITHRECEIVERS_DATE_RANGE_READY = 'POWITHRECEIVERS_DATE_RANGE_READY';
export const POWITHRECEIVERS_DATE_RANGE_NO_RECORDS = 'POWITHRECEIVERS_DATE_RANGE_NO_RECORDS';

// PO NO RECEIVERS
export const PONORECEIVERS_DATE_RANGE_NOT_READY = 'PONORECEIVERS_DATE_RANGE_NOT_READY';
export const PONORECEIVERS_DATE_RANGE_READY = 'PONORECEIVERS_DATE_RANGE_READY';
export const PONORECEIVERS_DATE_RANGE_NO_RECORDS = 'PONORECEIVERS_DATE_RANGE_NO_RECORDS';

// OPENPO EMAIL REPORT
export const OPENPOEMAIL_NO_RECORDS = 'OPENPOEMAIL_NO_RECORDS';
export const OPENPOEMAIL_DATE_RANGE_NOT_READY = 'OPENPOEMAIL_DATE_RANGE_NOT_READY';
export const OPENPOEMAIL_DATE_RANGE_READY = 'OPENPOEMAIL_DATE_RANGE_READY';
export const OPENPOEMAIL_DATE_RANGE_NO_RECORDS = 'OPENPOEMAIL_DATE_RANGE_NO_RECORDS';
export const OPENPOEMAIL_REVIEW_NOT_READY = 'OPENPOEMAIL_REVIEW_NOT_READY';
export const OPENPOEMAIL_REVIEW_READY = 'OPENPOEMAIL_REVIEW_READY';

/// state 3 - started
export const STARTED = 'STARTED';
// state 90 - FAILED
export const FAILURE = 'FAILURE';
// state 100 - Completed successfully
export const SUCCESS = 'SUCCESS';