export const STEP_0_START = 'STEP_0_START';
export const STEP_3_UP_TO_DATE = 'STEP_3_UP_TO_DATE';
export const STEP_5_ROLLBACK = 'STEP_5_ROLLBACK';
export const STEP_8_OUT_OF_RANGE = 'STEP_8_OUT_OF_RANGE';
export const STEP_10_GEN_RECEIVERS = 'STEP_10_GEN_RECEIVERS';
export const STEP_20_RECEIVER_INSERT_M2M = 'STEP_20_RECEIVER_INSERT_M2M';
export const STEP_30_PO_STATUS_UPDATE = 'STEP_30_PO_STATUS_UPDATE';
export const STEP_40_FINISH = 'STEP_40_FINISH';

